"""Add Thumbnail image field in User model

Revision ID: 9227990048c9
Revises: 839cfa57375e
Create Date: 2025-03-01 10:58:44.492076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9227990048c9'
down_revision: Union[str, None] = '839cfa57375e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_thumbnail_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_thumbnail_image')
    # ### end Alembic commands ###
